apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: lab8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: bitnami/spark:3.5.0
        env:
          - name: SPARK_MODE
            value: "worker"
          - name: SPARK_MASTER_URL
            value: "spark://spark-master:7077"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
