apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: lab8
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark:3.5.0
        env:
          - name: SPARK_MODE
            value: "master"
        ports:
        - containerPort: 7077
        - containerPort: 8081
        resources:
          requests:
            memory: "512Mi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: lab8
spec:
  type: NodePort
  ports:
  - name: spark-master
    port: 7077
    targetPort: 7077
    nodePort: 30007
  - name: spark-ui
    port: 8081
    targetPort: 8081
    nodePort: 30008
  selector:
    app: spark-master
